### PR TITLE
Connect to sqlite

### LINKED ISSUE #1: Connect to SQLite
Connect to the SQLite database, write data, and read data from it.

### PR DESCRIPTION
**Pull request by segara2410**
closes #1

### CODE REVIEW

**Review by threeal — CHANGES_REQUESTED** [review]
- Add test, we don't know whether this code will work or not, there's also no executable that could be used. Simply just connect to db, save config, load it, and compare it. As for the db connection, for testing purpose, i suggest to use memory instead of file as could be seen  in [here](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect).
- Save date as a Unix timestamp instead of a formatted string, i believe it's safer and more convenient to be used. Or better, just set the column to use `CURRENT_TIMESTAMP` as default. That makes it possible to skip setting the datetime each time a new data will be inserted.
- If `save()` require table, config, and return void, then `load()` should require table and return config. But why use `any`? if it's caused by `None` as a return alternative, you should use union of `str` and `None`. But better, just throw an error if table is not found or the query result is empty. After all, i don't think the `cursor.fetchall()` will always return list which atleast has length of 1 either.
- As in [this documentation](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.fetchall), `fetchall()` will return list. It will be inconvenient to be always need to call result with `[0]` operator just to access the string content. Use `fetchone()` instead and return config as `str` not as list nor object.
- I think it's possible to ignore the `table_exist()` function. In `load()`, just execute the `select` query whether the table is exist or not, if failed, it will throw an error, and you could just catch it. While in `save()` you could just execute a `create table if not exist` query before the `insert` query.
- Why using `ros2-ci@v0.4.2` if it already has the newest version? (`ros2-ci@v1.0.0`). But after all, there's no improvement in that version that is important for this project though.
- You could just ignored it, but i think you should be more consistent on how to format the query in `execute()` function. Always use type hint in function parameters and return value (even if it's `any` or `void`), and it's better to specify type hint in the object properties (in this case, it's `self.connection` and `self.cursor`).

**Review by threeal — CHANGES_REQUESTED** [review]
- As for the try catch, i mean it will be used during the function call, not inside the function. Using current function, probably you will called it like this:
  ```py
  config = handler.load(table)
  if config != None:
      # Do something
  else:
      print('Config not found!')
  ```
  While what i mean actually is this:
  ```py
  try:
      config = handler.load(table)
      # Do something
  except Exception as e:
      print('Failed to load config! %s' % e)
  ```
  So why catching exception inside the function if it's still required to check whether the result is `None` or not? Also, it's not fair to catch an exception in `load()` function while you just let the `save()` function to be called without any error handling.
- Previously, i believe you already put a `LIMIT` query during the `load()` function, why removed it?

**Review by threeal — APPROVED** [review]
Looks good to me.

**Review by maroqijalil — APPROVED** [review]
lgtm

**Pull request merged**
